# Generated by Django 4.1.7 on 2023-03-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_course_rating_course_videos_course_vidoes_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_videos', models.IntegerField(default=0)),
                ('number_of_videos_watched', models.IntegerField(default=0)),
                ('total_number_of_users', models.IntegerField(default=0)),
                ('total_progress_percent', models.FloatField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.course')),
            ],
        ),
    ]
