# Generated by Django 4.1.7 on 2023-03-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_quiz_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='organisation',
            new_name='organization',
        ),
    ]
