# Generated by Django 4.1.7 on 2023-03-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_organisation_course_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modules',
        ),
    ]
