# Generated by Django 4.1.7 on 2023-03-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_course_module_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='module_numbers',
            new_name='modules',
        ),
    ]
