# Generated by Django 4.1.7 on 2023-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_module_numbers_course_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
