# Generated by Django 4.1.7 on 2023-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_notes_number_video_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='notes_frequency',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='videos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
