# Generated by Django 4.1.7 on 2023-03-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_module_notes_frequency_alter_module_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_course',
            field=models.ImageField(blank=True, default='blank_course.png', null=True, upload_to='course/'),
        ),
    ]
