# Generated by Django 4.1.7 on 2023-03-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_course_image_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='modules',
            new_name='total_module',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='videos',
            new_name='total_video',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='notes_frequency',
            new_name='total_notes',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='videos',
            new_name='total_video',
        ),
    ]
