# Generated by Django 4.1.7 on 2023-03-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_organization_description_organization_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Organization', 'Organization')], default='Student', max_length=2000, null=True),
        ),
    ]
