# Generated by Django 4.1.7 on 2023-03-04 15:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teacher_organization_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='research_interests',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
