# Generated by Django 4.1.7 on 2023-03-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_organization_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='employees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
